# Generated by Django 4.2.4 on 2024-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peams_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_added', models.TimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('batch_no', models.CharField(max_length=50)),
                ('expired', models.BooleanField(default=False)),
                ('about_to_expire', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_to_expire', models.IntegerField()),
                ('expired', models.IntegerField()),
            ],
        ),
    ]
