# Generated by Django 4.2.4 on 2024-05-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peams_app', '0002_product_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.TimeField(auto_now=True),
        ),
    ]
