# Generated by Django 4.2.4 on 2024-05-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peams_app', '0005_alter_tracker_about_to_expire_alter_tracker_expired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
