# Generated by Django 4.2.4 on 2024-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peams_app', '0006_delete_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_status',
            field=models.CharField(default='okay', max_length=20),
        ),
    ]
