# Generated by Django 4.2.4 on 2024-06-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peams_app', '0007_product_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
